# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bb972da96421f10c907f8b80f5a3da05788d63d37d2989df7edee144228ca59117dd74fe0900abbeca5e0f1f74c8aa98e9cbcf1f604bb5bededc95371ec774fe

test:
  secret_key_base: 17896c73e66452b12aa7a5b6898a862b28322fbc80aea47653d9fce0d7da0574f23166cc5003ab5fcc4e492436c2fc2fdf961b085f0a6ce0d4ccaffeb5e3783a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
